import inquirer from "inquirer";
import { theme } from "./theme";

/**
 * Presents the generated commit title and body to the user for review and editing.
 * Allows confirming, editing title/body, or cancelling.
 * @param {string} initialTitle - The initial commit title generated by AI.
 * @param {string} initialBody - The initial commit body generated by AI.
 * @returns {Promise<{ title: string; body: string } | null>} - The final title/body object, or null if cancelled.
 */
export async function reviewAndConfirmCommitMessage(
	initialTitle: string,
	initialBody: string,
): Promise<{ title: string; body: string } | null> {
	let currentTitle = initialTitle;
	let currentBody = initialBody;

	while (true) {
		console.log(`\n${theme.primary("🤖 Generated Commit Message (Preview):")}`);
		console.log(`${theme.info("Title:")} ${currentTitle}`);
		console.log(
			`${theme.info("Body:")}\n${currentBody || theme.dim("(empty body)")}`,
		); // Show (empty body) if currentBody is empty

		const { action } = await inquirer.prompt([
			{
				type: "list",
				name: "action",
				message: "Review the generated commit message:",
				choices: [
					{ name: "✅ Confirm and Commit", value: "confirm" },
					{ name: "✏️ Edit Title", value: "edit_title" },
					{ name: "📝 Edit Body", value: "edit_body" },
					{ name: "❌ Cancel", value: "cancel" },
				],
			},
		]);

		switch (action) {
			case "confirm":
				return { title: currentTitle, body: currentBody };
			case "edit_title": {
				const { newTitle } = await inquirer.prompt([
					{
						type: "input",
						name: "newTitle",
						message: "Enter the new commit title:",
						default: currentTitle,
					},
				]);
				currentTitle = newTitle;
				break;
			}
			case "edit_body": {
				const { newBody } = await inquirer.prompt([
					{
						type: "editor", // Using editor for multi-line body input
						name: "newBody",
						message: "Edit the commit body (save and close editor to confirm):",
						default: currentBody,
						waitForUseInput: true,
					},
				]);
				currentBody = newBody;
				break;
			}
			case "cancel":
				console.log(theme.warning("Commit creation cancelled by user."));
				return null;
		}
	}
}
